import { useRouter } from "next/router";
import supabase from "@/utils/supabase";
import Head from "next/head";
import Banner from "@/components/Banner";
import {
	Button,
	Modal,
	ModalOverlay,
	ModalContent,
	ModalHeader,
	ModalFooter,
	ModalBody,
	ModalCloseButton,
	FormControl,
	Input,
	NumberInput,
	NumberInputField,
	NumberInputStepper,
	NumberIncrementStepper,
	NumberDecrementStepper,
	Select,
	Textarea,
	useToast,
	HStack,
} from "@chakra-ui/react";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import { useState, useEffect } from "react";
import { useDisclosure } from "@chakra-ui/react";

export async function getServerSideProps(context) {
	const { id } = context.query;

	const { data: novel, error: novelError } = await supabase
		.from("Novels")
		.select("*")
		.eq("id", id)
		.single();

	return {
		props: {
			novel,
		},
	};
}

export default function Novel({ novel }) {
	const router = useRouter();
	const { id } = router.query;
	const session = useSession();
	const [isInLibrary, setIsInLibrary] = useState(false);
	const [status, setStatus] = useState("Reading");
	const [score, setScore] = useState();
	const [progress, setProgress] = useState();
	const [dateStarted, setDateStarted] = useState();
	const [dateFinished, setDateFinished] = useState();
	const { isOpen, onOpen, onClose } = useDisclosure();
	const [isAdmin, setIsAdmin] = useState(false);
	const toast = useToast();

	const addToLibrary = async () => {
		const { data, error } = await supabase
			.from("Library")
			.select("*")
			.eq("user_id", session.user.id)
			.eq("novel_id", id);

		if (data?.length === 0 || data === null) {
			const { data, error } = await supabase.from("Library").insert([
				{
					user_id: session.user.id,
					novel_id: id,
					status: status,
					score: score,
					progress: progress,
					date_started: dateStarted,
					date_finished: dateFinished,
				},
			]);
		} else {
			const { data, error } = await supabase
				.from("Library")
				.update({
					status: status,
					score: score,
					progress: progress,
					date_started: dateStarted,
					date_finished: dateFinished,
				})
				.eq("user_id", session.user.id)
				.eq("novel_id", id);
		}
		if (!error) {
			setIsInLibrary(true);
			setStatus(status);
		}
	};

	useEffect(() => {
		if (session) {
			const checkLibrary = async () => {
				const { data, error } = await supabase
					.from("Library")
					.select("*")
					.eq("user_id", session.user.id)
					.eq("novel_id", id);

				if (data?.length === 0 || data === null) {
					setIsInLibrary(false);
				} else {
					setIsInLibrary(true);
					setScore(data[0].score);
					setStatus(data[0].status);
					setProgress(data[0].progress);
					setDateStarted(data[0].date_started);
					setDateFinished(data[0].date_finished);
				}
			};

			const checkAdmin = async () => {
				const { data, error } = await supabase
					.from("Users")
					.select("admin")
					.eq("id", session.user.id)
					.single();

				if (data.admin) {
					setIsAdmin(true);
				}
			};

			checkAdmin();
			checkLibrary();
		}
	}, [session]);

	const deleteFromLibrary = async () => {
		if (session && isInLibrary) {
			const { data, error } = await supabase
				.from("Library")
				.delete()
				.eq("user_id", session.user.id)
				.eq("novel_id", id);

			if (!error) {
				setIsInLibrary(false);
			}
		}
	};

	return (
		<>
			<Head>
				<title>{novel.title}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Banner title={""} file={novel.cover} />

			<div className="">
				<div className="">
					<img
						src={novel.cover}
						alt={novel.title}
						width="286px"
						height="400px"
					/>
					<HStack>
						{session && !isInLibrary && (
							<Button onClick={onOpen}>Add To Library</Button>
						)}
						{session && isInLibrary && (
							<Button onClick={onOpen}>{status}</Button>
						)}
						{session && isAdmin && <EditNovel novel={novel} />}
					</HStack>

					<Modal isOpen={isOpen} onClose={onClose}>
						<ModalOverlay />
						<ModalContent>
							<ModalHeader>{novel.title}</ModalHeader>
							<ModalCloseButton />
							<ModalBody>
								<FormControl
									id="status"
									isRequired
									display="flex"
									flexDirection="column"
								>
									<label>Status</label>
									<Select
										value={status}
										onChange={(e) => setStatus(e.target.value)}
										variant={"filled"}
									>
										<option value="Reading">Reading</option>
										<option value="Plan to Read">Plan to Read</option>
										<option value="Completed">Completed</option>
										<option value="On Hold">On Hold</option>
										<option value="Dropped">Dropped</option>
									</Select>

									<label>Score</label>
									<NumberInput
										max={10}
										min={0}
										value={score || 0}
										onChange={(value) => setScore(value)}
									>
										<NumberInputField />
										<NumberInputStepper>
											<NumberIncrementStepper />
											<NumberDecrementStepper />
										</NumberInputStepper>
									</NumberInput>

									<label>Progress</label>
									<NumberInput
										max={novel.chapters}
										min={0}
										value={progress || 0}
										onChange={(value) => setProgress(value)}
									>
										<NumberInputField />
										<NumberInputStepper>
											<NumberIncrementStepper />
											<NumberDecrementStepper />
										</NumberInputStepper>
									</NumberInput>

									<label>Date Started</label>
									<Input
										placeholder="Select Date"
										size="md"
										type="date"
										value={dateStarted}
										onChange={(e) => setDateStarted(e.target.value)}
									/>

									<label>Date Finished</label>
									<Input
										placeholder="Select Date"
										size="md"
										type="date"
										value={dateFinished}
										onChange={(e) => setDateFinished(e.target.value)}
									/>
								</FormControl>
							</ModalBody>
							<ModalFooter>
								<Button
									variant={"ghost"}
									colorScheme="red"
									onClick={async () => {
										await deleteFromLibrary();
										toast({
											title: "Novel removed from library",
											description: "Novel removed from library",
											status: "error",
											duration: 9000,
											isClosable: true,
										});
										onClose();
									}}
									size="sm"
								>
									Delete
								</Button>
								<Button
									variant="ghost"
									onClick={async () => {
										await addToLibrary();
										if (isInLibrary) {
											toast({
												title: "Novel added to library",
												description: "Novel added to library",
												status: "success",
												duration: 5000,
												isClosable: true,
											});
										} else {
											toast({
												title: "Novel updated in library",
												description: "Novel updated in library",
												status: "success",
												duration: 5000,
												isClosable: true,
											});
										}
										onClose();
									}}
									size="sm"
									mr={3}
								>
									Save
								</Button>
							</ModalFooter>
						</ModalContent>
					</Modal>

					<div className="flex flex-col items-center">
						<h1 className="text-2xl font-bold">{novel.title}</h1>
						<h2 className="text-xl font-bold">{novel.author}</h2>
					</div>
				</div>
				<div className="flex flex-col items-center">
					<h1 className="text-2xl font-bold">Synopsis</h1>
					<p className="text-xl">{novel.description}</p>
				</div>
			</div>
		</>
	);
}

function EditNovel({ novel }) {
	const {
		isOpen: isEditOpen,
		onOpen: onEditOpen,
		onClose: onEditClose,
	} = useDisclosure();

	const [title, setTitle] = useState(novel.title);
	const [author, setAuthor] = useState(novel.author);
	const [cover, setCover] = useState(novel.cover);
	const [description, setDescription] = useState(novel.description);
	const [id, setId] = useState(novel.id);

	const updateNovel = async () => {
		const { data, error } = await supabase
			.from("Novels")
			.update({
				title: title,
				author: author,
				cover: cover,
				description: description,
			})
			.eq("id", id);
	};

	return (
		<>
			<Button onClick={onEditOpen}>Edit Novel</Button>

			<Modal isOpen={isEditOpen} onClose={onEditClose}>
				<ModalOverlay />
				<ModalContent>
					<ModalHeader>Edit Novel</ModalHeader>
					<ModalCloseButton />
					<ModalBody>
						<FormControl id="title" isRequired>
							<label>Title</label>
							<Input
								type="text"
								value={title}
								onChange={(e) => setTitle(e.target.value)}
							/>
						</FormControl>
						<FormControl id="author" isRequired>
							<label>Author</label>
							<Input
								type="text"
								value={author}
								onChange={(e) => setAuthor(e.target.value)}
							/>
						</FormControl>
						<FormControl id="cover" isRequired>
							<label>Cover</label>
							<Input
								type="text"
								value={cover}
								onChange={(e) => setCover(e.target.value)}
							/>
						</FormControl>
						<FormControl id="description" isRequired>
							<label>Description</label>
							<Textarea
								value={description}
								onChange={(e) => setDescription(e.target.value)}
							/>
						</FormControl>
					</ModalBody>
					<ModalFooter>
						<Button
							variant={"ghost"}
							colorScheme="red"
							onClick={async () => {
								await updateNovel();
								window.location.reload();
								onEditClose();
							}}
							size="sm"
						>
							Update
						</Button>
					</ModalFooter>
				</ModalContent>
			</Modal>
		</>
	);
}
