import supabase from "@/utils/supabase";
import {
	Box,
	SimpleGrid,
	FormControl,
	FormLabel,
	Input,
	Button,
	InputGroup,
	InputLeftElement,
	IconButton,
	HStack,
} from "@chakra-ui/react";
import Link from "next/link";
import Banner from "@/components/Banner";
import Head from "next/head";
import { useState, useEffect } from "react";
import { HiSearch } from "react-icons/hi";

export async function getServerSideProps() {
	const { data, error } = await supabase.from("Novels").select("*");

	return {
		props: {
			novels: data,
		},
	};
}

export default function Novels({ novels }) {
	const [search, setSearch] = useState("");

	const handleInputChange = (e) => setSearch(e.target.value);

	const filteredNovels =
		search === ""
			? novels
			: novels.filter((novel) =>
					novel.title
						.toLowerCase()
						.replace(/\s+/g, "")
						.includes(search.toLowerCase().replace(/\s+/g, ""))
			  );

	return (
		<>
			<Head>
				<title>Novels</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Banner
				title={"Novels"}
				src={
					"https://byyeobrgzctlkancpgqd.supabase.co/storage/v1/object/public/banners/NovelBanner.webp"
				}
			/>

			<div className="flex min-h-screen flex-col items-center">
				<HStack className="mb-8">
					<InputGroup>
						<Input
							variant="filled"
							placeholder="Search"
							onChange={handleInputChange}
							value={search}
							width="20rem"
						/>
						<InputLeftElement
							pointerEvents="none"
							children={<HiSearch color="gray.300" />}
						/>
					</InputGroup>
				</HStack>

				<SimpleGrid columns={[2, 3, 4, 5, 6]} spacing="2rem" overflow="hidden">
					{filteredNovels.map((novel) => (
						<Link href={`/novels/${novel.id}`} key={novel.id}>
							<Box
								height="100%"
								width={{
									base: "200px",
								}}
								key={novel.id}
								className="hover:text-slate-500"
							>
								<img
									src={novel.cover}
									alt={novel.title}
									width="286px"
									height="400px"
									className="rounded-lg shadow-lg hover:border-2 hover:border-black hover:opacity-80"
								/>
								<p className="mx-2 mt-1 line-clamp-2">{novel.title}</p>
							</Box>
						</Link>
					))}
				</SimpleGrid>
			</div>
		</>
	);
}
