import Head from "next/head";
import Image from "next/image";
import { useSession } from "@supabase/auth-helpers-react";
import Banner from "@/components/Banner";

export default function Home() {
	const session = useSession();

	return (
		<>
			<Head>
				<title>Akari Novels</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Banner
				title={"Welcome"}
				src={
					"https://byyeobrgzctlkancpgqd.supabase.co/storage/v1/object/public/banners/HomeBanner.webp"
				}
			/>
		</>
	);
}
